[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../../libs/domain" }
infrastructure = { path = "../../libs/infrastructure" }
tokio = { workspace = true }
axum = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
anyhow = { workspace = true }
config = { workspace = true }
tower-http = { workspace = true }
sqlx = { workspace = true }
